### ISSUE TITLE
Main readme file needs completed with overview and sub topics

### ISSUE THREAD

**Issue by OwlWatcher** [tsytsykvitaliy/digital-forensics-network-forensics-challenge#1]
Everyone is assigned to completing this.

**Comment by OwlWatcher** [comment]
Section 1, 3, and 4 have been added. Section 2 is nearly done.

**Comment by tsytsykvitaliy** [comment]
Section 2 has been added. The only section left is references.

**Comment by OwlWatcher** [comment]
References has been added as well as the group photo. Closing this issue since the repo is complete.
